/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "toy-navy": "#1E1B4B",
        "toy-pink": "#FF6584",
        "toy-pink-light": "#FFF0F3",
        "toy-blue": "#38B6FF",
        "toy-blue-light": "#E8F7FF",
        "toy-yellow": "#FFDE59",
        "toy-yellow-light": "#FFFBE6",
        "toy-periwinkle": "#EAE8FE",
        "toy-lavender": "#F5F3FF",
        "toy-border": "#E5E1FB",
        "on-error-container": "#93000a",
        "background": "#faf8ff",
        "inverse-surface": "#2a3044",
        "on-tertiary-fixed-variant": "#004e5c",
        "outline-variant": "#c7c4d8",
        "error": "#ba1a1a",
        "primary-container": "#5852f6",
        "primary": "#3e33dd",
        "on-primary-container": "#eeebff",
        "secondary-fixed": "#ffdea8",
        "tertiary": "#005c6c",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface": "#faf8ff",
        "inverse-primary": "#c2c1ff",
        "surface-container-low": "#f2f3ff",
        "outline": "#777587",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#ffba20",
        "inverse-on-surface": "#eef0ff",
        "error-container": "#ffdad6",
        "surface-container": "#eaedff",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#cff4ff",
        "on-background": "#151b2e",
        "tertiary-container": "#00768a",
        "on-secondary-fixed": "#271900",
        "surface-container-highest": "#dce1fc",
        "primary-fixed-dim": "#c2c1ff",
        "surface-bright": "#faf8ff",
        "tertiary-fixed": "#acedff",
        "surface-variant": "#dce1fc",
        "on-primary-fixed": "#0d006a",
        "on-surface-variant": "#464555",
        "surface-container-lowest": "#ffffff",
        "secondary": "#7c5800",
        "on-surface": "#151b2e",
        "on-secondary-fixed-variant": "#5e4200",
        "surface-container-high": "#e3e7ff",
        "surface-dim": "#d3d9f3",
        "surface-tint": "#4a42e9",
        "on-tertiary-fixed": "#001f26",
        "on-secondary-container": "#6b4b00",
        "secondary-container": "#feb700",
        "tertiary-fixed-dim": "#4cd7f6",
        "primary-fixed": "#e2dfff",
        "on-primary-fixed-variant": "#2f1fd2"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "gutter-mobile": "1rem",
        "gutter": "1.5rem",
        "space-sm": "0.5rem",
        "margin-mobile": "1rem",
        "space-xl": "2.5rem",
        "margin": "2rem",
        "space-xs": "0.25rem"
      },
      fontFamily: {
        "label-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "display-hero-mobile": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "display-hero": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "toy": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "label-lg": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "700" }],
        "display-hero-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "800" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "display-hero": ["44px", { "lineHeight": "54px", "fontWeight": "800" }],
        "headline-lg-mobile": ["26px", { "lineHeight": "34px", "fontWeight": "700" }],
        "body-md": ["15px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
